// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40kWwSICYQUXBZ1J8xlK5Hg6JLni9pPM',
    appId: '1:289315107284:web:0d183590e5922ab2fbe641',
    messagingSenderId: '289315107284',
    projectId: 'gogreen-d6011',
    authDomain: 'gogreen-d6011.firebaseapp.com',
    storageBucket: 'gogreen-d6011.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsy9PRtb77V0ac94LLcVraXtzvpbbQfZM',
    appId: '1:289315107284:android:97391f97fe323958fbe641',
    messagingSenderId: '289315107284',
    projectId: 'gogreen-d6011',
    storageBucket: 'gogreen-d6011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Q5FMEhOaJoAZDsh7tQSuZw7wzK1MY5Q',
    appId: '1:289315107284:ios:6bdf8ef5bac71c56fbe641',
    messagingSenderId: '289315107284',
    projectId: 'gogreen-d6011',
    storageBucket: 'gogreen-d6011.appspot.com',
    iosBundleId: 'com.tapps.gogreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Q5FMEhOaJoAZDsh7tQSuZw7wzK1MY5Q',
    appId: '1:289315107284:ios:4abaaa4f7fbf3ee6fbe641',
    messagingSenderId: '289315107284',
    projectId: 'gogreen-d6011',
    storageBucket: 'gogreen-d6011.appspot.com',
    iosBundleId: 'com.tapps.gogreen.RunnerTests',
  );
}
